customhost = "database-1.ccdrt1n1eqbc.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "welcome2021"
customdb = "database-1"
custombucket = "addemployee58769"
customregion = "us-east-1"
